import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { safeErrorMessage } from "./safe-error-message.ts";

const LAST_RESORT = "Could not complete that request. Please try again.";

describe("safeErrorMessage", () => {
  it("keeps a short app error", () => {
    assert.equal(safeErrorMessage(new Error("Staffer not found in this organization"), "fallback"), "Staffer not found in this organization");
  });

  it("does not toast CloudFront HTML or gateway status text", () => {
    const html = `<!DOCTYPE html><html><body>ERROR: The request could not be satisfied. Generated by cloudfront (504)</body></html>`;
    assert.equal(safeErrorMessage(new Error(html), "Could not save"), "Could not save");
    assert.equal(safeErrorMessage(new Error("504 Gateway Timeout"), "Could not save"), "Could not save");
  });

  it("never returns CloudFront 403 HTML even when fallback is the same HTML", () => {
    const html = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><body><h1>403 ERROR</h1><h2>Request blocked</h2><p>Generated by cloudfront (CloudFront)</p></body></html>`;
    assert.equal(safeErrorMessage(new Error(html), html), LAST_RESORT);
    assert.equal(safeErrorMessage(new Error("403 ERROR Request blocked"), html), LAST_RESORT);
  });

  it("uses the fallback for empty or oversized messages", () => {
    assert.equal(safeErrorMessage(null, "Could not reset"), "Could not reset");
    assert.equal(safeErrorMessage(new Error("x".repeat(300)), "Could not save"), "Could not save");
  });
});
