project_id = "dhrrukdcigiiqksibdfb"

[functions.send-email]
verify_jwt = true

[functions.parse-referral-doc]
verify_jwt = true

[functions.parse-recipe-doc]
verify_jwt = true

[functions.suggest-meal-swaps]
verify_jwt = true

[functions.estimate-meal-nutrition]
verify_jwt = true

[functions.detect-doc-dates]
verify_jwt = true

[functions.auth-send-email]
verify_jwt = false
