// Every permission key the app checks with can(key) / requirePermission(key),
// folded into the category + minimum setting that grants it
// (docs/downloads/hive-access-levels-and-permissions.xlsx, sheet 5).
// null = HIVE-internal; never granted through agency access.

import type { CategoryId } from "./categories.ts";

export const PERMISSION_KEYS = {
  invite_staff: ["staff_hiring", "edit"],
  view_staff_records: ["staff_roster", "view"],
  edit_staff_records: ["staff_roster", "edit"],
  manage_staff_roles: ["agency_settings", "edit"],
  deactivate_staff: ["staff_hiring", "edit"],
  view_staff_documents: ["staff_compliance", "view"],
  upload_staff_documents: ["staff_compliance", "edit"],
  approve_staff_documents: ["staff_compliance", "edit"],
  view_clients: ["clients", "view"],
  edit_client_records: ["clients", "edit"],
  manage_client_intake: ["clients", "edit"],
  view_client_medical: ["client_medical", "view"],
  edit_client_medical: ["client_medical", "edit"],
  view_client_documents: ["clients", "view"],
  manage_client_documents: ["clients", "edit"],
  manage_client_goals: ["clients", "edit"],
  edit_shift_notes: ["documentation", "edit"],
  approve_shift_notes: ["documentation", "edit"],
  view_daily_logs: ["documentation", "view"],
  approve_daily_logs: ["documentation", "edit"],
  manage_forms: ["agency_settings", "edit"],
  view_form_submissions: ["documentation", "view"],
  approve_form_submissions: ["documentation", "edit"],
  view_compliance_dashboard: ["staff_compliance", "view"],
  file_staff_documents: ["staff_compliance", "edit"],
  manage_obligations: ["staff_compliance", "edit"],
  view_audit_trail: ["reports", "view"],
  view_incidents: ["incidents", "view"],
  manage_incidents: ["incidents", "edit"],
  export_incident_reports: ["incidents", "edit"],
  manage_medications: ["client_medical", "edit"],
  view_hrc: ["hrc", "view"],
  manage_hrc: ["hrc", "edit"],
  manage_organization_settings: ["agency_settings", "edit"],
  manage_service_codes: ["billing", "edit"],
  view_analytics: ["reports", "view"],
  export_reports: ["reports", "edit"],
  manage_permissions: ["agency_settings", "edit"],
  manage_roles: ["agency_settings", "edit"],
  assign_training: ["staff_compliance", "edit"],
  create_courses: ["staff_compliance", "edit"],
  edit_courses: ["staff_compliance", "edit"],
  manage_certifications: ["staff_compliance", "edit"],
  manage_programs: ["staff_compliance", "edit"],
  approve_external_certs: ["staff_compliance", "edit"],
  view_team_reports: ["staff_compliance", "view"],
  manage_organization: ["agency_settings", "edit"],
  view_platform_metrics: null,
  manage_all_orgs: null,
  view_referrals: ["hosts", "view"],
  manage_referrals: ["hosts", "edit"],
  send_emails: ["agency_settings", "edit"],
  view_schedule: ["scheduling", "view"],
  create_shifts: ["scheduling", "edit"],
  edit_shifts: ["scheduling", "edit"],
  delete_shifts: ["scheduling", "edit"],
  approve_shift_swaps: ["scheduling", "edit"],
  manage_recurring_shifts: ["scheduling", "edit"],
  view_team_timesheets: ["timesheets", "view"],
  view_all_timesheets: ["timesheets", "view"],
  approve_timesheets: ["timesheets", "edit"],
  edit_timesheets: ["timesheets", "edit"],
  export_evv: ["timesheets", "edit"],
  view_billing: ["billing", "view"],
  manage_billing: ["billing", "edit"],
  view_payroll: ["payroll", "view"],
  manage_payroll: ["payroll", "edit"],
  view_financial_reports: ["financial_reports", "view"],
  export_financial_reports: ["financial_reports", "edit"],
  view_financial_tns_gross: ["financial_reports", "view"],
  view_financial_rhs: ["financial_reports", "view"],
  view_financial_employees: ["financial_reports", "view"],
  view_own_timesheets: ["phone_app", "edit"],
  submit_shift_notes: ["phone_app", "edit"],
  submit_daily_logs: ["phone_app", "edit"],
  submit_forms: ["phone_app", "edit"],
  complete_obligations: ["phone_app", "edit"],
  report_incidents: ["phone_app", "edit"],
  view_emar: ["phone_app", "edit"],
  submit_emar: ["phone_app", "edit"],
  upload_external_certs: ["phone_app", "edit"],
  view_own_training: ["phone_app", "edit"],
  view_certifications: ["phone_app", "edit"],
} as const satisfies Record<string, readonly [CategoryId, "view" | "edit"] | null>;

export type Permission = keyof typeof PERMISSION_KEYS;
export const ALL_PERMISSIONS = Object.keys(PERMISSION_KEYS) as Permission[];

export function isPermission(key: string): key is Permission {
  return Object.prototype.hasOwnProperty.call(PERMISSION_KEYS, key);
}
