const GATEWAY_NOISE =
  /cloudfront|gateway timeout|timed out|504|502|503|403|request blocked|request could not be satisfied|generated by cloudfront|<!doctype|<html[\s>]|the request could not be satisfied|too much traffic|configuration error/i;

const LAST_RESORT_ERROR = "Could not complete that request. Please try again.";

function extractErrorText(error: unknown): string {
  if (typeof error === "string") return error;
  if (error instanceof Error) {
    const parts = [error.message];
    if (error.cause instanceof Error) parts.push(error.cause.message);
    else if (typeof error.cause === "string") parts.push(error.cause);
    return parts.filter(Boolean).join(" ");
  }
  if (error && typeof error === "object" && "message" in error) {
    const message = (error as { message?: unknown }).message;
    if (typeof message === "string") return message;
  }
  return "";
}

function isSafeUserMessage(text: string): boolean {
  const trimmed = text.replace(/\s+/g, " ").trim();
  if (!trimmed || trimmed.length > 240) return false;
  return !GATEWAY_NOISE.test(trimmed);
}

/**
 * Map server-fn / gateway failures to short UI copy.
 * Never return CloudFront / WAF HTML, even if the caller passed it as fallback
 * (the Profile Save toast did that and painted the 403 page over the form).
 */
export function safeErrorMessage(error: unknown, fallback: string): string {
  const raw = extractErrorText(error).replace(/\s+/g, " ").trim();
  const safeFallback = isSafeUserMessage(fallback) ? fallback.replace(/\s+/g, " ").trim() : LAST_RESORT_ERROR;
  if (!raw || !isSafeUserMessage(raw)) return safeFallback;
  return raw;
}
