/**
 * Curated Evidence pack catalog — ported from the product demo.
 * Staff / Client / Company catalogs do not share rows except Host Home Cert.
 */

import { evvServiceLabel } from "../evv-codes.ts";
import {
  CLIENT_QUIZ_CODES,
  EVIDENCE_CADENCE_OPTIONS,
  SERVICE_CODE_FLAGS,
  STAFF_QUIZ_CODES,
  type EvidenceHelpLink,
  type EvidencePackDef,
  type EvidenceRequirementDef,
  type EvidenceSubject,
  type QuestionnaireAnswers,
  type ServiceCodeFlag,
  type SuggestedPack,
} from "./types.ts";

export const EVIDENCE_HELP_LINKS = {
  oig: { label: "Search the OIG exclusion list", href: "https://exclusions.oig.hhs.gov/" },
  dspd: { label: "DSPD provider resources", href: "https://dspd.utah.gov/" },
  forms: { label: "DSPD provider forms", href: "https://dspd.utah.gov/providers/forms/" },
  medicaid: { label: "Utah Medicaid provider manuals", href: "https://medicaid.utah.gov/" },
  rules: {
    label: "Utah Admin Rules (R539)",
    href: "https://adminrules.utah.gov/public/rule/R539/Current%20Rules",
  },
  coc: { label: "DHHS / DSPD provider info", href: "https://dspd.utah.gov/providers/" },
  host: {
    label: "Host Home Certification (DSPD forms)",
    href: "https://dspd.utah.gov/providers/forms/",
  },
  disclosure: {
    label: "Employee Medicaid Disclosure (DSPD forms)",
    href: "https://dspd.utah.gov/providers/forms/",
  },
  usor: { label: "Utah State Office of Rehabilitation", href: "https://jobs.utah.gov/usor/" },
} as const satisfies Record<string, EvidenceHelpLink>;

function req(
  partial: Omit<EvidenceRequirementDef, "shortLabel" | "links"> & {
    shortLabel?: string;
    links?: readonly EvidenceHelpLink[];
  },
): EvidenceRequirementDef {
  return {
    ...partial,
    shortLabel: partial.shortLabel ?? partial.title,
    links: partial.links ?? [],
  };
}

export const EVIDENCE_REQUIREMENTS: readonly EvidenceRequirementDef[] = [
  req({
    key: "cpr_first_aid",
    title: "CPR / First Aid",
    evidenceType: "upload",
    attestationText: null,
    cadence: "every_2_years",
    sowCite: "SOW §1.8(5)",
    cadenceDisplay: "Every 2 years · SOW §1.8(5)",
    why: "Keep a current CPR and first aid certificate for staff who support people you serve. Renew before expiration so someone is prepared in a medical emergency.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "background_screening",
    title: "Background screening",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.9(2)",
    cadenceDisplay: "Annual · SOW §1.9(2)",
    why: "Utah requires a DHHS background check through the Office of Background Processing before—and while—someone works with people you serve. Store the clearance result on this file.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "thirty_day_orientation",
    title: "30-day orientation",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW §1.8(4)",
    cadenceDisplay: "Once · SOW §1.8(4)",
    why: "New staff must complete orientation (rights, abuse reporting, agency policies, person-specific needs, and related topics) within 30 days. Upload completion proof or finish training in the platform.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "medicaid_disclosure",
    title: "Medicaid Disclosure",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.13.5",
    cadenceDisplay: "Annual · SOW §1.13.5",
    why: "Staff complete a Medicaid disclosure form confirming they understand program rules. Keep the signed form on the staff file and renew annually.",
    links: [EVIDENCE_HELP_LINKS.disclosure],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "oig_exclusion",
    title: "OIG / fraud exclusion check",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.9(7)",
    cadenceDisplay: "Annual · SOW §1.9(7)",
    why: "Confirm this person is not on the federal OIG exclusion list (individuals barred from federal health programs). Run the search, save a screenshot or printout, and re-check on your schedule.",
    links: [EVIDENCE_HELP_LINKS.oig],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "code_of_conduct",
    title: "Code of Conduct acknowledgment",
    evidenceType: "attestation",
    attestationText: "I have read the agency Code of Conduct and agree to follow it while working.",
    cadence: "annual",
    sowCite: "CST / R380-80",
    cadenceDisplay: "Annual · CST / R380-80",
    why: "Staff should read your Code of Conduct and confirm they understand expectations for working with people, families, and colleagues. DSPD/DHHS provider materials can help if you are building or updating yours.",
    links: [EVIDENCE_HELP_LINKS.coc, EVIDENCE_HELP_LINKS.dspd],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "conflict_of_interest",
    title: "Conflict of Interest disclosure",
    evidenceType: "attestation",
    attestationText: "I have disclosed any conflicts of interest as required by agency policy.",
    cadence: "annual",
    sowCite: "CST",
    cadenceDisplay: "Annual · CST",
    why: "Staff disclose outside employment, family relationships, or financial ties that could affect their work. This protects the people you serve and supports transparency with the State.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "driving_record",
    title: "Driving record (MVR)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.30",
    cadenceDisplay: "Annual · SOW §1.30",
    why: "If this person transports people you support, obtain a motor vehicle record and confirm their driving history meets your agency policy.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "driver_license",
    title: "Driver license",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §1.30",
    cadenceDisplay: "On expiry · SOW §1.30",
    why: "Keep a copy of a valid driver license for anyone who transports. Replace it when the license is renewed or updated.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "auto_insurance_proof",
    title: "Auto insurance proof",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.30",
    cadenceDisplay: "Annual · SOW §1.30",
    why: "If they use a personal vehicle for work transport, keep current insurance proof on file for agency coverage and audit readiness.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "transport_safety_attest",
    title: "Transport safety attestation",
    evidenceType: "attestation",
    attestationText: "I will follow agency transport rules when driving people we support.",
    cadence: "once",
    sowCite: "SOW §1.30",
    cadenceDisplay: "Once · SOW §1.30",
    why: "A short signed statement confirming they will follow agency transport rules (seat belts, no phone use while driving, approved practices, and related expectations).",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "abi_training",
    title: "ABI training",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW §1.8(8)",
    cadenceDisplay: "Once before alone · SOW §1.8(8)",
    why: "Staff who work alone with a person who has an acquired brain injury need ABI-specific training first. Upload completion proof before that assignment begins.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "mandt_behavior",
    title: "Behavior intervention certification",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §1.8(6)",
    cadenceDisplay: "On expiry · SOW §1.8(6)",
    why: "If this person may support people with aggressive behavior, they need an approved behavior-intervention certification (Mandt or equivalent). Keep certification current.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "host_home_cert",
    title: "Host Home Certification",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §11.5",
    cadenceDisplay: "Annual · SOW §11.5",
    why: "Before Host Home services—and annually afterward—the home must be inspected and certified as safe and appropriate for the person’s needs. Use DSPD’s Host Home Certification form or an equivalent checklist covering the same elements. The same file also appears on the client record.",
    links: [EVIDENCE_HELP_LINKS.host],
    subject: "staff",
    dualLink: "host_home_cert",
  }),
  req({
    key: "host_age_21",
    title: "Host age ≥21",
    evidenceType: "attestation",
    attestationText: "I confirm this host is at least 21 years of age.",
    cadence: "once",
    sowCite: "SOW §11.6",
    cadenceDisplay: "Once · SOW §11.6",
    why: "Host Home hosts must be at least 21 years of age. Confirm once and retain that confirmation on the host’s staff file.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "sei_prior_training",
    title: "SEI prior training",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW §30.5 / §30.6.c",
    cadenceDisplay: "Once · SOW §30.5 / §30.6.c",
    why: "Staff delivering Supported Employment for an Individual need SEI-specific training before they begin. Upload proof of completion here.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "sei_acre",
    title: "ACRE certification",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §30.6.b",
    cadenceDisplay: "On expiry · SOW §30.6.b",
    why: "The agency must maintain at least one ACRE-certified staff member. If this person holds that credential, keep their ACRE certificate on file.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "bc1_staff_cred",
    title: "BC1 staff credential",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §3.6",
    cadenceDisplay: "On expiry · SOW §3.6",
    why: "Behavior Consultation I staff must meet Option A or B (experience, degree, and DOPL license or exemption). Upload licenses, transcripts, and any exemption letter that applies.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "bc2_staff_cred",
    title: "BC2 staff credential",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §4.6",
    cadenceDisplay: "On expiry · SOW §4.6",
    why: "BC2 allows several credential paths (BCaBA/LaBA, master’s with RBS/RaBS, supervised student pathway, or DOPL exemption). Keep documentation that matches the path this staff member uses.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "bc3_staff_cred",
    title: "BC3 staff credential",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §5.6",
    cadenceDisplay: "On expiry · SOW §5.6",
    why: "BC3 applies to complex or dangerous behavior cases. Staff must meet a BC3 pathway (BCBA with LBA, doctorate with psychologist license, supervised BCBA-student path, or DOPL exemption). Upload the matching credentials.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "client_photo",
    title: "Photograph",
    evidenceType: "upload",
    attestationText: null,
    cadence: "every_5_years",
    sowCite: "SOW §1.10(3)",
    cadenceDisplay: "Every 5 years · SOW §1.10(3)",
    why: "Keep a current photograph in the person’s file so staff and emergency responders can identify them. Replace it at least every five years, or sooner if appearance changes significantly.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "client_pcsp",
    title: "Current PCSP on file",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §1.10",
    cadenceDisplay: "As updated · SOW §1.10",
    why: "The Person-Centered Support Plan (PCSP) is the State’s plan for this person’s services and goals. Keep the current PCSP and updates readily available for staff and auditors.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "grievance_receipt",
    title: "Grievance signed receipt",
    evidenceType: "attestation",
    attestationText: "Person/guardian received and acknowledged the grievance procedure.",
    cadence: "once",
    sowCite: "SOW §1.10(11)",
    cadenceDisplay: "Once on admit · SOW §1.10(11)",
    why: "At admission, the person or guardian must receive your grievance process in writing and acknowledge receipt. This documents that they know how to raise concerns.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "support_strategies",
    title: "Support Strategies",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §1.24(5)",
    cadenceDisplay: "With PCSP · SOW §1.24(5)",
    why: "Support Strategies describe how staff will help with PCSP goals day to day. Keep the current strategies with the person’s file (a BSP serves this role for behavior consultation).",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "clinical_legal_uploads",
    title: "Clinical / legal file uploads",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §1.10",
    cadenceDisplay: "As needed · SOW §1.10",
    why: "Store medical, dental, DNR, guardianship, and related documents staff may need. Upload only what applies to this person.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "host_home_cert_client",
    title: "Host Home Certification",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §11.5",
    cadenceDisplay: "Annual · SOW §11.5",
    why: "Same home certification as on the host’s staff file. Demonstrates that the residence where this person lives has been inspected and certified.",
    links: [EVIDENCE_HELP_LINKS.host],
    subject: "client",
    dualLink: "host_home_cert",
  }),
  req({
    key: "room_board_agreement",
    title: "Room & board agreement",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §11.3.9",
    cadenceDisplay: "Current · SOW §11.3.9",
    why: "Written agreement covering room and board for the Host Home arrangement. Keep it current for as long as the person lives there.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "belongings_inventory_hhs",
    title: "Belongings inventory",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §11.3.5",
    cadenceDisplay: "Annual · SOW §11.3.5",
    why: "A dated inventory of the person’s belongings in the home. Supports accountability if items are missing and is commonly reviewed in residential audits.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "housemate_discussion",
    title: "Housemate informed discussion",
    evidenceType: "attestation",
    attestationText: "Informed discussion about housemate(s) was completed.",
    cadence: "keep_current",
    sowCite: "SOW §1.35",
    cadenceDisplay: "On change · SOW §1.35",
    why: "When housemates change in HHS, PPS, or RHS, document that you discussed living arrangements and preferences with the person.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "lease_housing",
    title: "Lease / housing agreement",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "RHS residence",
    cadenceDisplay: "Current",
    why: "For residential habilitation, keep the lease or housing agreement that documents where the person lives and under what terms.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "form_930",
    title: "Form 930 (enhanced staffing)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §21.3.4",
    cadenceDisplay: "Before enhanced · SOW §21.3.4",
    why: "If this person receives enhanced staffing, Form 930 must be complete before that level of support begins. Skip this item if enhanced staffing does not apply.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "belongings_inventory_rhs",
    title: "Belongings inventory",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §21.3.7",
    cadenceDisplay: "Annual · SOW §21.3.7",
    why: "Same purpose as the HHS inventory: a dated list of belongings for the residential setting.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "fba_on_file",
    title: "FBA on file",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §3/4/5.3",
    cadenceDisplay: "Per SOW timelines · §3/4/5.3",
    why: "A Functional Behavior Assessment (FBA) explains why target behaviors occur. Keep the completed FBA in the person’s file and update it when the plan changes.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "bsp_on_file",
    title: "BSP on file",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §3/4/5.4",
    cadenceDisplay: "Monthly reevaluate · §3/4/5.4",
    why: "The Behavior Support Plan (BSP) guides how staff respond and teach replacement skills. Keep the current BSP here; behavior consultants reevaluate it monthly.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "employment_supports",
    title: "Employment supports / strategies",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §30.2.7",
    cadenceDisplay: "As updated · SOW §30.2.7",
    why: "Written plans for helping this person maintain or increase job independence. Update when the job or supports change.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "company_bylaws",
    title: "Bylaws / governing documents",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §1.14",
    cadenceDisplay: "As updated · SOW §1.14",
    why: "Bylaws and governing documents describe how your agency is organized (board, ownership, and decision-making). Auditors may request them; keep a current copy available. Update only when the organization changes.",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_board_minutes",
    title: "Board minutes",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §1.14",
    cadenceDisplay: "As updated · SOW §1.14",
    why: "Board minutes record who attended and what was decided. Keep them organized so leadership can produce them quickly if DSPD requests them (often within a few days).",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_personnel_pp",
    title: "Personnel policies & job descriptions",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.17",
    cadenceDisplay: "Annual review · SOW §1.17",
    why: "Written personnel policies and a job description for each role set expectations for hiring, duties, and workplace conduct. Review annually and upload the current packet.",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_operating_pp",
    title: "Operating policies & procedures",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.18",
    cadenceDisplay: "Annual review · SOW §1.18",
    why: "Operating policies cover day-to-day service delivery, records, transport, incidents, and related practices. Keep the current playbook available to staff.",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_health_pp",
    title: "Health support policies",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.23",
    cadenceDisplay: "Annual review · SOW §1.23",
    why: "Health support policies describe how your agency handles medications, emergencies, and when to call 911. They give staff clear direction in medical situations.",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_hrc",
    title: "Human Rights Committee established",
    evidenceType: "attestation",
    attestationText: "Our agency has a Human Rights Committee that meets Utah rule requirements.",
    cadence: "keep_current",
    sowCite: "SOW §1.20",
    cadenceDisplay: "Once / maintain · SOW §1.20",
    why: "Most providers must maintain a Human Rights Committee that reviews rights restrictions. Attest that yours exists and meets Utah rule requirements; keep detailed meeting records in your usual process.",
    links: [EVIDENCE_HELP_LINKS.rules],
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_hrp",
    title: "Human Rights Plan",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §1.21",
    cadenceDisplay: "As updated · SOW §1.21",
    why: "A written Human Rights Plan describes how your agency protects and restores rights. Upload the current plan (some limited service types may be exempt—confirm in your SOW).",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_coc_posted",
    title: "Code of Conduct posted / client rights",
    evidenceType: "attestation",
    attestationText:
      "Code of Conduct / client rights materials are posted or provided and reviewed annually.",
    cadence: "annual",
    sowCite: "CST",
    cadenceDisplay: "Annual · CST",
    why: "People you serve should have access to their rights information and your conduct expectations. Confirm materials are posted or provided, and review them annually.",
    links: [EVIDENCE_HELP_LINKS.coc],
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_insurance",
    title: "Insurance certificates",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "CST",
    cadenceDisplay: "On expiry · CST",
    why: "Proof your agency carries required insurance (general liability, auto if you transport, and professional liability when applicable). Replace files when policies renew.",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_medicaid_enrollment",
    title: "Medicaid standing / manuals awareness",
    evidenceType: "upload",
    attestationText: null,
    cadence: "annual",
    sowCite: "SOW §1.7",
    cadenceDisplay: "Annual · SOW §1.7",
    why: "Document that the agency remains in good standing with Medicaid and that leadership is familiar with the manuals and rules under which you bill. Often a memo plus enrollment letters.",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_baa",
    title: "BAA documentation",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "HIPAA",
    cadenceDisplay: "As updated · HIPAA",
    why: "Business Associate Agreements with vendors who handle protected health information. Keep signed BAAs available to demonstrate HIPAA arrangements if requested.",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "company_custom",
    title: "Custom company requirement",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "Agency",
    cadenceDisplay: "You set · Agency",
    why: "Add an agency-only custom item (for example an internal checklist). This is optional and not required by the SOW.",
    subject: "company",
    dualLink: null,
  }),
  req({
    key: "slh_person_training",
    title: "SLH person-specific training",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW SLH",
    cadenceDisplay: "As assigned · SOW SLH",
    why: "Staff delivering Supported Living Hourly need documented training on this person’s supports, home, and safety needs before working alone. Upload the sign-off or training record.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "sln_natural_supports",
    title: "SLN natural-supports orientation",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW SLN",
    cadenceDisplay: "Once · SOW SLN",
    why: "Natural-support staff should complete orientation on the person’s plan, rights, and how SLN hours are used. Keep the signed orientation on this file.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "sjd_acre",
    title: "ACRE certification (SJD)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §33.5",
    cadenceDisplay: "Within 60 days · SOW §33.5",
    why: "Supported Job Development staff need ACRE certification, including customized employment, within 60 days of hire. Upload the current certificate.",
    links: [EVIDENCE_HELP_LINKS.usor],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "customized_employment_usu",
    title: "Customized Employment training (USU)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW §29.4 / §33.5",
    cadenceDisplay: "Before serving · SOW §29.4 / §33.5",
    why: "SEE and SJD staff complete USU Customized Employment training before delivering those services. Upload the completion certificate.",
    links: [EVIDENCE_HELP_LINKS.usor, EVIDENCE_HELP_LINKS.forms],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "sed_acre",
    title: "ACRE certification (SED)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §28.4",
    cadenceDisplay: "On expiry · SOW §28.4",
    why: "Staff delivering Supported Employment in a Group need a current ACRE certificate. Upload it here and replace it when it expires.",
    links: [EVIDENCE_HELP_LINKS.usor],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "sec_coworker_orient",
    title: "Co-worker employment orientation",
    evidenceType: "attestation",
    attestationText:
      "I completed orientation for supporting this person alongside a co-worker at the job site.",
    cadence: "once",
    sowCite: "SOW SEC",
    cadenceDisplay: "Once · SOW SEC",
    why: "Supported Employment with a Co-worker needs a short orientation so the DSPD staff member and workplace co-worker know roles, safety, and fading supports.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "sjp_milestone_packet",
    title: "SJP placement milestone packet",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW SJP",
    cadenceDisplay: "At placement · SOW SJP",
    why: "Keep the Initial Job Placement milestone documentation (job start proof and required DSPD/CIE forms) on this staff file when they close a placement.",
    links: [EVIDENCE_HELP_LINKS.forms],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "sjr_retention_packet",
    title: "SJR retention milestone packet",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW SJR",
    cadenceDisplay: "At retention · SOW SJR",
    why: "Upload Job Retention milestone evidence when the required retention period is met. Use DSPD CIE milestone forms when those apply.",
    links: [EVIDENCE_HELP_LINKS.forms],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "epr_staff_ready",
    title: "EPR staff readiness",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW EPR",
    cadenceDisplay: "Before serving · SOW EPR",
    why: "Employment Preparation staff should have documented readiness (training plus any extra-hours request forms) before delivering EPR. Additional EPR hours use the DSPD request form.",
    links: [EVIDENCE_HELP_LINKS.forms],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "day_supports_staff",
    title: "Day supports staff assignment",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §7 / §8",
    cadenceDisplay: "As assigned · SOW §7 / §8",
    why: "For DSI, DSG, or DSP, keep proof this person was oriented to the day program, ratios, and the people they support. Site licenses live on the company file; this is the staff assignment record.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "rhs_residential_staff",
    title: "RHS residential staff assignment",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §21",
    cadenceDisplay: "As assigned · SOW §21",
    why: "Staff covering a staffed home need documented orientation to that home’s people, emergency plan, and overnight expectations. Upload the home-specific sign-off.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "pps_foster_license",
    title: "Child-placing / foster license (PPS)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §20.5",
    cadenceDisplay: "On expiry · SOW §20.5",
    why: "Professional Parent Supports hosts need a current DHHS Office of Licensing child-placing or foster-care license. Upload the license and replace it when it expires.",
    links: [EVIDENCE_HELP_LINKS.forms],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "cmp_cms_caregiver_training",
    title: "Caregiver compensation training",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW §32.5",
    cadenceDisplay: "Before serving · SOW §32.5",
    why: "CMP and CMS caregivers complete DSPD’s New Caregiver Compensation training (passing score required) before paid family caregiver hours. Upload the completion record.",
    links: [EVIDENCE_HELP_LINKS.forms, EVIDENCE_HELP_LINKS.dspd],
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "hsq_sanitary_training",
    title: "HSQ clean and safe home training",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW Article 12",
    cadenceDisplay: "Once · SOW Article 12",
    why: "Homemaker staff need training on keeping a clean, sanitary, and safe living environment before HSQ visits. Upload the training record.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "pm1_lpn_license",
    title: "LPN license (PM1)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW PM1",
    cadenceDisplay: "On expiry · SOW PM1",
    why: "Professional Medication Monitoring LPN staff must keep a current Utah LPN license on file. Upload the license and replace it at renewal.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "pm2_rn_license",
    title: "RN license (PM2)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW PM2",
    cadenceDisplay: "On expiry · SOW PM2",
    why: "Professional Medication Monitoring RN staff must keep a current Utah RN license on file. Upload the license and replace it at renewal.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "pn1_nursing_license",
    title: "Nursing license (PN1)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW PN1",
    cadenceDisplay: "On expiry · SOW PN1",
    why: "Professional Nursing Service I requires a current nursing license that matches the service. Keep the license on this file; visit notes stay on Daily Logs.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "pn2_nursing_license",
    title: "Nursing license (PN2)",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW PN2",
    cadenceDisplay: "On expiry · SOW PN2",
    why: "Professional Nursing Service II requires a current license for that nursing level. Upload it here. Monthly nursing summaries stay on Summaries, not this row.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "pba_competency",
    title: "PBA competency sign-off",
    evidenceType: "attestation",
    attestationText:
      "I understand Personal Budget Assistant duties and will not commingle or misuse the person’s funds.",
    cadence: "once",
    sowCite: "SOW PBA",
    cadenceDisplay: "Once · SOW PBA",
    why: "Staff who help with a personal budget should confirm they understand money-handling rules. Monthly financial statements stay in Finances; this is the one-time staff sign-off.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "els_staff_ready",
    title: "ELS staff assignment",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW ELS",
    cadenceDisplay: "As assigned · SOW ELS",
    why: "Extended Living Supports staff need a documented assignment to the overnight or extended window they cover. Upload the assignment or orientation record.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "tfb_trainer_ready",
    title: "TFB trainer readiness",
    evidenceType: "upload",
    attestationText: null,
    cadence: "once",
    sowCite: "SOW TFB",
    cadenceDisplay: "Once · SOW TFB",
    why: "Family and Individual Training staff should have documented readiness to teach the curriculum they will deliver. Upload the trainer sign-off or certificate.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "hourly_direct_support",
    title: "Hourly direct-support assignment",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW PAC / COM / RP",
    cadenceDisplay: "As assigned · SOW PAC / COM / RP",
    why: "For PAC, COM, RP2, or RP3, keep person-specific assignment training on this file. Clock-in and EVV stay on shifts; this row is the personnel proof they were prepared for that person.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "respite_overnight_staff",
    title: "Overnight respite staff assignment",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW RP4 / RP5 / RPS",
    cadenceDisplay: "As assigned · SOW RP4 / RP5 / RPS",
    why: "Overnight or camp respite staff need documented orientation to the site, sleeping arrangements, and the people they support. Upload that sign-off.",
    subject: "staff",
    dualLink: null,
  }),
  req({
    key: "slh_living_agreement",
    title: "SLH living / support agreement",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW SLH",
    cadenceDisplay: "Current · SOW SLH",
    why: "Keep the current Supported Living Hourly agreement that describes where supports happen and who provides them. Update it when the arrangement changes.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "day_program_plan",
    title: "Day program / community plan",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §7 / §8",
    cadenceDisplay: "As updated · SOW §7 / §8",
    why: "For DSI, DSG, or DSP, keep the current day-program or community-participation plan that staff follow. Daily attendance stays on shifts, not this row.",
    subject: "client",
    dualLink: null,
  }),
  req({
    key: "employment_supports_sjd",
    title: "Job development plan",
    evidenceType: "upload",
    attestationText: null,
    cadence: "keep_current",
    sowCite: "SOW §33",
    cadenceDisplay: "As updated · SOW §33",
    why: "Keep the current job-development plan for this person. Monthly UPI summaries are entered by admin elsewhere; this is the working plan on the person file.",
    links: [EVIDENCE_HELP_LINKS.forms],
    subject: "client",
    dualLink: null,
  }),
] as const;

function hasCode(answers: QuestionnaireAnswers, code: ServiceCodeFlag): boolean {
  return answers.serviceCodes.includes(code);
}

export const EVIDENCE_PACKS: readonly EvidencePackDef[] = [
  {
    key: "all_staff",
    title: "All-staff",
    chip: "All-staff",
    subject: "staff",
    description: "Personnel file suggested for every staff member.",
    requirementKeys: [
      "cpr_first_aid",
      "background_screening",
      "thirty_day_orientation",
      "medicaid_disclosure",
      "oig_exclusion",
      "code_of_conduct",
      "conflict_of_interest",
    ],
    when: () => true,
  },
  {
    key: "transport",
    title: "Transport",
    chip: "Transport",
    subject: "staff",
    description: "Driving record, license, insurance, and transport rules.",
    requirementKeys: [
      "driving_record",
      "driver_license",
      "auto_insurance_proof",
      "transport_safety_attest",
    ],
    when: (a) => a.transportsPeople,
  },
  {
    key: "abi",
    title: "ABI",
    chip: "ABI",
    subject: "staff",
    description: "ABI training before working alone with an ABI caseload.",
    requirementKeys: ["abi_training"],
    when: (a) => a.worksWithAbi,
  },
  {
    key: "mandt_behavior",
    title: "Mandt / behavior",
    chip: "Mandt / behavior",
    subject: "staff",
    description: "Behavior-intervention certification when aggression risk applies.",
    requirementKeys: ["mandt_behavior"],
    when: (a) => a.maySupportAggressiveBehavior,
  },
  {
    key: "hhs_staff",
    title: "HHS host",
    chip: "HHS host",
    subject: "staff",
    description: "Host Home Certification — same file dual-linked to the HHS client.",
    requirementKeys: ["host_home_cert", "host_age_21"],
    when: (a) => hasCode(a, "HHS"),
  },
  {
    key: "sei",
    title: "SEI",
    chip: "SEI",
    subject: "staff",
    description: "SEI prior training and ACRE certification.",
    requirementKeys: ["sei_prior_training", "sei_acre"],
    when: (a) => hasCode(a, "SEI"),
  },
  {
    key: "bc1_staff",
    title: "BC1",
    chip: "BC1",
    subject: "staff",
    description: "BC1 staff credential on the personnel file.",
    requirementKeys: ["bc1_staff_cred"],
    when: (a) => hasCode(a, "BC1"),
  },
  {
    key: "bc2_staff",
    title: "BC2",
    chip: "BC2",
    subject: "staff",
    description: "BC2 staff credential on the personnel file.",
    requirementKeys: ["bc2_staff_cred"],
    when: (a) => hasCode(a, "BC2"),
  },
  {
    key: "bc3_staff",
    title: "BC3",
    chip: "BC3",
    subject: "staff",
    description: "BC3 staff credential on the personnel file.",
    requirementKeys: ["bc3_staff_cred"],
    when: (a) => hasCode(a, "BC3"),
  },
  {
    key: "client_core",
    title: "Client file",
    chip: "Client file",
    subject: "client",
    description: "Photograph, PCSP, grievance, strategies, and clinical uploads.",
    requirementKeys: [
      "client_photo",
      "client_pcsp",
      "grievance_receipt",
      "support_strategies",
      "clinical_legal_uploads",
    ],
    when: () => true,
  },
  {
    key: "hhs_client",
    title: "HHS residence",
    chip: "HHS residence",
    subject: "client",
    description: "Host Home Certification plus residence paperwork.",
    requirementKeys: [
      "host_home_cert_client",
      "room_board_agreement",
      "belongings_inventory_hhs",
      "housemate_discussion",
    ],
    when: (a) => hasCode(a, "HHS"),
  },
  {
    key: "rhs_client",
    title: "RHS residence",
    chip: "RHS residence",
    subject: "client",
    description: "Lease, Form 930, and belongings inventory.",
    requirementKeys: ["lease_housing", "form_930", "belongings_inventory_rhs"],
    when: (a) => hasCode(a, "RHS"),
  },
  {
    key: "bc_client",
    title: "Behavior consultation file",
    chip: "Behavior consultation",
    subject: "client",
    description: "FBA and BSP for BC1 / BC2 / BC3.",
    requirementKeys: ["fba_on_file", "bsp_on_file"],
    when: (a) => hasCode(a, "BC1") || hasCode(a, "BC2") || hasCode(a, "BC3"),
  },
  {
    key: "slh_staff",
    title: "SLH",
    chip: "SLH",
    subject: "staff",
    description: "Person-specific training for Supported Living Hourly.",
    requirementKeys: ["slh_person_training"],
    when: (a) => hasCode(a, "SLH"),
  },
  {
    key: "sln_staff",
    title: "SLN",
    chip: "SLN",
    subject: "staff",
    description: "Natural-supports orientation for SLN staff.",
    requirementKeys: ["sln_natural_supports"],
    when: (a) => hasCode(a, "SLN"),
  },
  {
    key: "sjd_staff",
    title: "SJD",
    chip: "SJD",
    subject: "staff",
    description: "ACRE and Customized Employment for job development.",
    requirementKeys: ["sjd_acre", "customized_employment_usu"],
    when: (a) => hasCode(a, "SJD"),
  },
  {
    key: "see_staff",
    title: "SEE",
    chip: "SEE",
    subject: "staff",
    description: "Customized Employment training for enterprise employment.",
    requirementKeys: ["customized_employment_usu"],
    when: (a) => hasCode(a, "SEE"),
  },
  {
    key: "sed_staff",
    title: "SED",
    chip: "SED",
    subject: "staff",
    description: "ACRE for group supported employment.",
    requirementKeys: ["sed_acre"],
    when: (a) => hasCode(a, "SED"),
  },
  {
    key: "sec_staff",
    title: "SEC",
    chip: "SEC",
    subject: "staff",
    description: "Co-worker employment orientation.",
    requirementKeys: ["sec_coworker_orient"],
    when: (a) => hasCode(a, "SEC"),
  },
  {
    key: "sjp_staff",
    title: "SJP",
    chip: "SJP",
    subject: "staff",
    description: "Initial job placement milestone packet.",
    requirementKeys: ["sjp_milestone_packet"],
    when: (a) => hasCode(a, "SJP"),
  },
  {
    key: "sjr_staff",
    title: "SJR",
    chip: "SJR",
    subject: "staff",
    description: "Job retention milestone packet.",
    requirementKeys: ["sjr_retention_packet"],
    when: (a) => hasCode(a, "SJR"),
  },
  {
    key: "epr_staff",
    title: "EPR",
    chip: "EPR",
    subject: "staff",
    description: "Employment preparation staff readiness.",
    requirementKeys: ["epr_staff_ready"],
    when: (a) => hasCode(a, "EPR"),
  },
  {
    key: "day_supports_staff",
    title: "Day supports",
    chip: "Day supports",
    subject: "staff",
    description: "Assignment training for DSI, DSG, or DSP.",
    requirementKeys: ["day_supports_staff"],
    when: (a) => hasCode(a, "DSI") || hasCode(a, "DSG") || hasCode(a, "DSP"),
  },
  {
    key: "rhs_staff",
    title: "RHS",
    chip: "RHS",
    subject: "staff",
    description: "Home-specific residential staff assignment.",
    requirementKeys: ["rhs_residential_staff"],
    when: (a) => hasCode(a, "RHS"),
  },
  {
    key: "pps_staff",
    title: "PPS",
    chip: "PPS",
    subject: "staff",
    description: "Child-placing / foster license for professional parents.",
    requirementKeys: ["pps_foster_license"],
    when: (a) => hasCode(a, "PPS"),
  },
  {
    key: "cmp_cms_staff",
    title: "CMP / CMS",
    chip: "CMP / CMS",
    subject: "staff",
    description: "DSPD caregiver compensation training.",
    requirementKeys: ["cmp_cms_caregiver_training"],
    when: (a) => hasCode(a, "CMP") || hasCode(a, "CMS"),
  },
  {
    key: "hsq_staff",
    title: "HSQ",
    chip: "HSQ",
    subject: "staff",
    description: "Clean and safe home training for homemaker staff.",
    requirementKeys: ["hsq_sanitary_training"],
    when: (a) => hasCode(a, "HSQ"),
  },
  {
    key: "pm1_staff",
    title: "PM1",
    chip: "PM1",
    subject: "staff",
    description: "Current LPN license.",
    requirementKeys: ["pm1_lpn_license"],
    when: (a) => hasCode(a, "PM1"),
  },
  {
    key: "pm2_staff",
    title: "PM2",
    chip: "PM2",
    subject: "staff",
    description: "Current RN license.",
    requirementKeys: ["pm2_rn_license"],
    when: (a) => hasCode(a, "PM2"),
  },
  {
    key: "pn1_staff",
    title: "PN1",
    chip: "PN1",
    subject: "staff",
    description: "Current nursing license for PN1.",
    requirementKeys: ["pn1_nursing_license"],
    when: (a) => hasCode(a, "PN1"),
  },
  {
    key: "pn2_staff",
    title: "PN2",
    chip: "PN2",
    subject: "staff",
    description: "Current nursing license for PN2.",
    requirementKeys: ["pn2_nursing_license"],
    when: (a) => hasCode(a, "PN2"),
  },
  {
    key: "pba_staff",
    title: "PBA",
    chip: "PBA",
    subject: "staff",
    description: "One-time money-handling competency (not monthly statements).",
    requirementKeys: ["pba_competency"],
    when: (a) => hasCode(a, "PBA"),
  },
  {
    key: "els_staff",
    title: "ELS",
    chip: "ELS",
    subject: "staff",
    description: "Extended living staff assignment.",
    requirementKeys: ["els_staff_ready"],
    when: (a) => hasCode(a, "ELS"),
  },
  {
    key: "tfb_staff",
    title: "TFB",
    chip: "TFB",
    subject: "staff",
    description: "Family and individual training readiness.",
    requirementKeys: ["tfb_trainer_ready"],
    when: (a) => hasCode(a, "TFB"),
  },
  {
    key: "hourly_direct_staff",
    title: "Hourly direct support",
    chip: "Hourly support",
    subject: "staff",
    description: "Person-specific assignment for PAC, COM, RP2, or RP3.",
    requirementKeys: ["hourly_direct_support"],
    when: (a) => hasCode(a, "PAC") || hasCode(a, "COM") || hasCode(a, "RP2") || hasCode(a, "RP3"),
  },
  {
    key: "overnight_respite_staff",
    title: "Overnight / camp respite",
    chip: "Overnight respite",
    subject: "staff",
    description: "Site assignment for RP4, RP5, or RPS.",
    requirementKeys: ["respite_overnight_staff"],
    when: (a) => hasCode(a, "RP4") || hasCode(a, "RP5") || hasCode(a, "RPS"),
  },
  {
    key: "sei_client",
    title: "Employment (SEI / SEE / SED)",
    chip: "Employment",
    subject: "client",
    description: "Employment supports and strategies.",
    requirementKeys: ["employment_supports"],
    when: (a) => hasCode(a, "SEI") || hasCode(a, "SEE") || hasCode(a, "SED"),
  },
  {
    key: "sjd_client",
    title: "Job development file",
    chip: "Job development",
    subject: "client",
    description: "Current job-development plan.",
    requirementKeys: ["employment_supports_sjd"],
    when: (a) => hasCode(a, "SJD"),
  },
  {
    key: "slh_client",
    title: "SLH living",
    chip: "SLH living",
    subject: "client",
    description: "Supported living hourly agreement.",
    requirementKeys: ["slh_living_agreement"],
    when: (a) => hasCode(a, "SLH"),
  },
  {
    key: "day_client",
    title: "Day program file",
    chip: "Day program",
    subject: "client",
    description: "Day program or community plan for DSI / DSG / DSP.",
    requirementKeys: ["day_program_plan"],
    when: (a) => hasCode(a, "DSI") || hasCode(a, "DSG") || hasCode(a, "DSP"),
  },
  {
    key: "company_governance",
    title: "Governance",
    chip: "Governance",
    subject: "company",
    description: "Bylaws and board minutes.",
    requirementKeys: ["company_bylaws", "company_board_minutes"],
    when: () => true,
  },
  {
    key: "company_policies",
    title: "Policies & procedures",
    chip: "Policies & procedures",
    subject: "company",
    description: "Personnel, operating, and health support policies.",
    requirementKeys: ["company_personnel_pp", "company_operating_pp", "company_health_pp"],
    when: () => true,
  },
  {
    key: "company_rights",
    title: "Rights",
    chip: "Rights",
    subject: "company",
    description: "Human Rights Committee, plan, and posted rights.",
    requirementKeys: ["company_hrc", "company_hrp", "company_coc_posted"],
    when: () => true,
  },
  {
    key: "company_standing",
    title: "Agency standing",
    chip: "Agency standing",
    subject: "company",
    description: "Insurance, Medicaid standing, and BAAs.",
    requirementKeys: ["company_insurance", "company_medicaid_enrollment", "company_baa"],
    when: () => true,
  },
  {
    key: "company_optional",
    title: "Optional agency customs",
    chip: "Optional",
    subject: "company",
    description: "Optional agency-only custom slot.",
    requirementKeys: ["company_custom"],
    when: (a) => a.includeCompanyCustoms,
  },
] as const;

const REQ_BY_KEY = new Map(EVIDENCE_REQUIREMENTS.map((r) => [r.key, r]));
const PACK_BY_KEY = new Map(EVIDENCE_PACKS.map((p) => [p.key, p]));

export function requirementByKey(key: string): EvidenceRequirementDef | null {
  return REQ_BY_KEY.get(key) ?? null;
}

export function packByKey(key: string): EvidencePackDef | null {
  return PACK_BY_KEY.get(key) ?? null;
}

export function packsForSubject(subject: EvidenceSubject): EvidencePackDef[] {
  return EVIDENCE_PACKS.filter((p) => p.subject === subject);
}

export function requirementsForPack(packKey: string): EvidenceRequirementDef[] {
  const pack = packByKey(packKey);
  if (!pack) return [];
  return pack.requirementKeys
    .map((key) => requirementByKey(key))
    .filter((row): row is EvidenceRequirementDef => !!row);
}

export function defaultQuestionnaireAnswers(subject: EvidenceSubject): QuestionnaireAnswers {
  return {
    subject,
    serviceCodes: [],
    transportsPeople: subject === "staff",
    worksWithAbi: false,
    maySupportAggressiveBehavior: false,
    includeCompanyCustoms: false,
  };
}

export function suggestPacks(answers: QuestionnaireAnswers): SuggestedPack[] {
  return EVIDENCE_PACKS.filter(
    (pack) => pack.subject === answers.subject && pack.when(answers),
  ).map((pack) => ({ pack, reason: pack.description }));
}

export function suggestedRequirementKeys(answers: QuestionnaireAnswers): string[] {
  const keys = new Set<string>();
  for (const row of suggestPacks(answers)) {
    for (const key of row.pack.requirementKeys) keys.add(key);
  }
  return [...keys];
}

export function chipsForRequirementKey(
  key: string,
  suggested: readonly SuggestedPack[] = [],
): string[] {
  const fromSuggested = suggested
    .filter((row) => row.pack.requirementKeys.includes(key))
    .map((row) => row.pack.chip);
  if (fromSuggested.length > 0) return [...new Set(fromSuggested)];
  return [
    ...new Set(EVIDENCE_PACKS.filter((p) => p.requirementKeys.includes(key)).map((p) => p.chip)),
  ];
}

export function isSowSuggestedKey(key: string, answers: QuestionnaireAnswers): boolean {
  if (!suggestedRequirementKeys(answers).includes(key)) return false;
  const sow = requirementByKey(key)?.sowCite ?? "";
  return /SOW/i.test(sow);
}

export function hostHomeDualLinkPeerKey(requirementKey: string): string | null {
  if (requirementKey === "host_home_cert") return "host_home_cert_client";
  if (requirementKey === "host_home_cert_client") return "host_home_cert";
  return null;
}

export function isBuiltInTaxFormKey(key: string): boolean {
  return /^(w-?9|i-?9)$/i.test(key.trim());
}

export function cadenceLabel(cadence: string): string {
  const found = EVIDENCE_CADENCE_OPTIONS.find((row) => row.value === cadence);
  return found?.label ?? "Once";
}

export function evidenceTypeLabel(type: string): string {
  return type === "attestation" ? "Attestation" : "Upload";
}

export function parseServiceCodeFlags(raw: readonly string[]): ServiceCodeFlag[] {
  const allowed = new Set<string>(SERVICE_CODE_FLAGS);
  const out: ServiceCodeFlag[] = [];
  for (const value of raw) {
    const code = value.trim().toUpperCase();
    if (!allowed.has(code)) continue;
    if (!out.includes(code as ServiceCodeFlag)) out.push(code as ServiceCodeFlag);
  }
  return out;
}

export function quizCodesForSubject(subject: EvidenceSubject): readonly ServiceCodeFlag[] {
  if (subject === "client") return CLIENT_QUIZ_CODES;
  if (subject === "staff") return STAFF_QUIZ_CODES;
  return [];
}

export function quizCodeLabel(code: ServiceCodeFlag): string {
  const labeled = evvServiceLabel(code);
  return labeled && labeled !== code ? labeled : code;
}

/** Keys that must never appear on another subject's catalog (except the HHS dual-link pair). */
export function catalogSubjectsArePartitioned(): boolean {
  const seen = new Map<string, EvidenceSubject>();
  for (const row of EVIDENCE_REQUIREMENTS) {
    const prev = seen.get(row.key);
    if (prev && prev !== row.subject) return false;
    seen.set(row.key, row.subject);
  }
  return true;
}
