/**
 * Write the agency-setup question-to-requirement coverage artifact: every
 * one of the 85 docs/compliance/dhhs91172/Applicability_Facts.json rows,
 * how it is answered (agency questionnaire / deferred to a later record /
 * derived / a static rule), and which REQ- keys it feeds.
 * Usage: node --experimental-strip-types scripts/report-agency-setup-coverage.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  AGENCY_SETUP_QUESTIONS,
  AGENCY_SETUP_QUESTIONS_VERSION,
  AGENCY_SETUP_SECTION_LABELS,
  NON_QUESTION_FACT_DISPOSITIONS,
  workbookFact,
  workbookFactIds,
} from "../src/lib/obligations/agency-setup-questions.ts";
import {
  COMPOUND_SPLIT_FACT_IDS,
  DEFERRED_FACTS,
} from "../src/lib/obligations/deferred-setup-facts.ts";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "../docs/compliance/dhhs91172");

type Row = {
  factId: string;
  scope: string;
  disposition: string;
  question: string;
  detail: string;
  requirementCount: number;
  requirementIds: string[];
};

function buildRows(): Row[] {
  const rows: Row[] = [];

  for (const q of AGENCY_SETUP_QUESTIONS) {
    for (const factId of q.sourceFactIds) {
      const raw = workbookFact(factId)!;
      rows.push({
        factId,
        scope: raw.fact_scope,
        disposition: `Agency questionnaire — "${AGENCY_SETUP_SECTION_LABELS[q.section]}"`,
        question: q.question,
        detail: q.sourceNote ?? "",
        requirementCount: Number(raw.requirements_affected) || 0,
        requirementIds: raw.linked_requirement_keys
          .split(",")
          .map((s) => s.trim())
          .filter(Boolean),
      });
    }
  }

  for (const f of DEFERRED_FACTS) {
    const raw = workbookFact(f.factId)!;
    const storageDetail =
      f.storage.kind === "generic"
        ? `New field on the ${f.deferredTo.replace("_record", "")} record.`
        : f.storage.description;
    rows.push({
      factId: f.factId,
      scope: raw.fact_scope,
      disposition: `Deferred to ${f.deferredTo.replace("_record", " record")}`,
      question: f.question,
      detail: [storageDetail, f.sourceNote].filter(Boolean).join(" "),
      requirementCount: Number(raw.requirements_affected) || 0,
      requirementIds: f.sourceRequirementIdsRaw
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    });
  }

  for (const nd of NON_QUESTION_FACT_DISPOSITIONS) {
    const raw = workbookFact(nd.factId)!;
    rows.push({
      factId: nd.factId,
      scope: raw.fact_scope,
      disposition:
        nd.disposition === "derived"
          ? "Derived (no question asked)"
          : "Static platform rule (no question asked)",
      question: raw.question,
      detail: nd.detail,
      requirementCount: Number(raw.requirements_affected) || 0,
      requirementIds: raw.linked_requirement_keys
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    });
  }

  return rows.sort((a, b) => a.factId.localeCompare(b.factId, undefined, { numeric: true }));
}

function checkExhaustive(rows: Row[]): { missing: string[]; unexpectedDupes: string[] } {
  const all = new Set(workbookFactIds());
  const counts = new Map<string, number>();
  for (const r of rows) counts.set(r.factId, (counts.get(r.factId) ?? 0) + 1);
  const missing = [...all].filter((id) => !counts.has(id));
  const compound = new Set(COMPOUND_SPLIT_FACT_IDS);
  const unexpectedDupes = [...counts.entries()]
    .filter(([id, n]) => n > 1 && !compound.has(id))
    .map(([id]) => id);
  return { missing, unexpectedDupes };
}

function formatMarkdown(rows: Row[]): string {
  const { missing, unexpectedDupes } = checkExhaustive(rows);
  const totalReqIds = new Set(rows.flatMap((r) => r.requirementIds));
  const lines: string[] = [];
  lines.push("# Agency setup — question-to-requirement coverage");
  lines.push("");
  lines.push(`Registry version: ${AGENCY_SETUP_QUESTIONS_VERSION}.`);
  lines.push(
    `Every row of docs/compliance/dhhs91172/Applicability_Facts.json (${workbookFactIds().length} facts) is accounted for exactly once below (a compound fact split across two rows is the only exception, flagged in its Detail column). Generated by scripts/report-agency-setup-coverage.ts — do not hand-edit.`,
  );
  lines.push("");
  lines.push("## Exhaustiveness check");
  lines.push("");
  lines.push(
    `- Workbook facts with no row below: ${missing.length === 0 ? "none" : missing.join(", ")}`,
  );
  lines.push(
    `- Facts claimed more than once without being a declared compound split: ${unexpectedDupes.length === 0 ? "none" : unexpectedDupes.join(", ")}`,
  );
  lines.push(
    `- Distinct REQ- keys reachable from an agency-level answer or a deferred-record answer: ${totalReqIds.size}`,
  );
  lines.push("");
  lines.push("## Coverage table");
  lines.push("");
  lines.push("| Fact ID | Workbook scope | How it's answered | Question | Detail | Reqs |");
  lines.push("| --- | --- | --- | --- | --- | ---: |");
  for (const r of rows) {
    const question = r.question.replace(/\|/g, "\\|");
    const detail = (r.detail || "").replace(/\|/g, "\\|").replace(/\n/g, " ");
    lines.push(
      `| ${r.factId} | ${r.scope} | ${r.disposition} | ${question} | ${detail} | ${r.requirementCount} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const rows = buildRows();
  const { missing, unexpectedDupes } = checkExhaustive(rows);
  if (missing.length > 0 || unexpectedDupes.length > 0) {
    throw new Error(
      `Coverage is not exhaustive — missing: [${missing.join(", ")}], unexpected dupes: [${unexpectedDupes.join(", ")}]`,
    );
  }
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "AGENCY_SETUP_COVERAGE.md"), formatMarkdown(rows));
  writeFileSync(join(outDir, "AGENCY_SETUP_COVERAGE.json"), JSON.stringify(rows, null, 2));
  console.log(
    `Wrote coverage for ${rows.length} rows (${workbookFactIds().length} workbook facts).`,
  );
}

main();
