import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import {
  applyExecutableBatchOverlays,
  buildCatalogCoverageReport,
  formatCatalogCoverageMarkdown,
} from "./catalog-coverage.ts";
import { DHHS91172_CATALOG_DIR, readCommittedCatalog } from "./draft-rules/catalog-fs.ts";
import { VERIFIED_PUBLICATIONS } from "./draft-rules/verified-publication.ts";
import { committedPublicationIssues } from "./draft-rules/controlled-publication.ts";

describe("DHHS91172 catalog coverage", () => {
  it("covers every imported parent and treats elements as children, not tasks", () => {
    const report = buildCatalogCoverageReport(readCommittedCatalog());
    assert.equal(report.counts.importedParents, 760);
    assert.equal(report.counts.importedElements, 607);
    assert.equal(report.counts.importedRows, 1367);
    assert.ok(report.counts.executable >= 140);
    assert.equal(report.counts.published, 50);
    assert.equal(report.counts.verified, 50);
    assert.equal(report.counts.wiredFirstBatch, 5);
    assert.equal(report.counts.wiredSecondBatch, 6);
    assert.equal(report.counts.wiredThirdBatch, 3);
    assert.equal(report.counts.wiredFourthBatch, 4);
    assert.equal(report.counts.wiredFifthBatch, 2);
    assert.equal(report.counts.wiredSixthBatch, 2);
    assert.equal(report.counts.wiredSeventhBatch, 10);
    assert.equal(report.counts.wiredEighthBatch, 9);
    assert.equal(report.counts.wiredMegaC, 9);
    assert.equal(report.counts.wiredNinthBatch, 15);
    assert.equal(report.counts.wiredTenthBatch, 41);
    assert.equal(report.counts.wiredEleventhBatch, 34);
    assert.equal(report.counts.wired, 140);
    assert.equal(report.counts.remainingExecutable, 0);
    assert.equal(VERIFIED_PUBLICATIONS.length, 50);
    assert.deepEqual(
      committedPublicationIssues(applyExecutableBatchOverlays(readCommittedCatalog().parents)),
      [],
    );

    const committed = JSON.parse(
      readFileSync(join(DHHS91172_CATALOG_DIR, "COVERAGE_REPORT.json"), "utf8"),
    ) as { counts: typeof report.counts };
    assert.deepEqual(committed.counts, report.counts);
    const markdown = formatCatalogCoverageMarkdown(report);
    assert.match(markdown, /Controlled publication \(Soft=none\)/);
    assert.match(markdown, /None\. All 140 live-key parents have a fixture overlay/);

    const driving = report.rows.find((r) => r.requirementKey === "REQ-1.30");
    assert.ok(driving);
    assert.equal(driving.liveKey, "driving_record_transport");
    assert.equal(driving.canPublish, true);
    assert.equal(driving.canActivate, true);
    assert.equal(driving.mintsStaffTask, false);
    assert.equal(report.counts.elementOfParent, 607);

    const orientation = report.rows.find((r) => r.requirementKey === "REQ-1.8.4");
    assert.ok(orientation);
    assert.equal(orientation.role, "parent");
    assert.equal(orientation.liveKey, "orientation_30_day");
    assert.equal(orientation.implementationStatus, "live_mapped");
    assert.equal(orientation.mintsStaffTask, false);
    assert.equal(orientation.canPublish, true);
    assert.equal(orientation.canActivate, true);
    assert.equal(orientation.publication, "published");

    const usor = report.rows.find((r) => r.requirementKey === "REQ-30.6.a");
    assert.ok(usor);
    assert.equal(usor.liveKey, "usor_job_coaching_sei");
    assert.equal(usor.canPublish, true);
    assert.equal(usor.canActivate, true);
    const sjdAcre = report.rows.find((r) => r.requirementKey === "REQ-33.5.b");
    assert.ok(sjdAcre);
    assert.equal(sjdAcre.liveKey, "acre_sjd");
    assert.equal(sjdAcre.canPublish, true);
    assert.equal(sjdAcre.canActivate, true);
    const sjdCe = report.rows.find((r) => r.requirementKey === "REQ-33.5.c");
    assert.ok(sjdCe);
    assert.equal(sjdCe.liveKey, "customized_employment_usu");
    assert.equal(sjdCe.canPublish, true);
    assert.equal(sjdCe.canActivate, true);

    const periodic = report.rows.find((r) => r.requirementKey === "REQ-1.25");
    assert.ok(periodic);
    assert.equal(periodic.liveKey, "sei_monthly_summary_upi");
    assert.equal(periodic.canPublish, true);
    assert.equal(periodic.canActivate, true);
    const seiMonthly = report.rows.find((r) => r.requirementKey === "REQ-30.3.4");
    assert.ok(seiMonthly);
    assert.equal(seiMonthly.liveKey, "sei_monthly_summary_upi");
    assert.equal(seiMonthly.canPublish, true);
    const cmpMonthly = report.rows.find((r) => r.requirementKey === "REQ-32.3.2");
    assert.ok(cmpMonthly);
    assert.equal(cmpMonthly.liveKey, "cmp_cms_monthly_summaries");
    assert.equal(cmpMonthly.canPublish, true);
    const sjdMonthly = report.rows.find((r) => r.requirementKey === "REQ-33.3.4");
    assert.ok(sjdMonthly);
    assert.equal(sjdMonthly.liveKey, "sjd_monthly_summary_upi");
    assert.equal(sjdMonthly.canPublish, true);

    const notes = report.rows.find((r) => r.requirementKey === "REQ-1.10.7");
    assert.ok(notes);
    assert.equal(notes.liveKey, "timesheets_attendance");
    assert.equal(notes.canPublish, true);
    assert.equal(notes.canActivate, true);
    assert.equal(notes.mintsStaffTask, false);
    const evv = report.rows.find((r) => r.requirementKey === "REQ-1.12");
    assert.ok(evv);
    assert.equal(evv.liveKey, "evv_visit_verification");
    assert.equal(evv.canPublish, true);
    assert.equal(evv.canActivate, true);
    assert.equal(evv.mintsStaffTask, false);

    const background = report.rows.find((r) => r.requirementKey === "REQ-1.9.2");
    assert.ok(background);
    assert.equal(background.liveKey, "background_screening_annual");
    assert.equal(background.canPublish, true);
    assert.equal(background.canActivate, true);
    assert.equal(background.mintsStaffTask, false);
    const medicaid101 = report.rows.find((r) => r.requirementKey === "REQ-1.7.1");
    assert.ok(medicaid101);
    assert.equal(medicaid101.liveKey, "medicaid_101_contractor");
    assert.equal(medicaid101.canPublish, true);
    const enrollment = report.rows.find((r) => r.requirementKey === "REQ-1.4.1");
    assert.ok(enrollment);
    assert.equal(enrollment.liveKey, "medicaid_enrollment");
    assert.equal(enrollment.canPublish, true);
    const umbrella = report.rows.find((r) => r.requirementKey === "REQ-1.9");
    assert.ok(umbrella);
    assert.equal(umbrella.liveKey, "ce_12h_annual");
    assert.equal(umbrella.canPublish, true);
    assert.equal(umbrella.canActivate, true);
    const grievance = report.rows.find((r) => r.requirementKey === "REQ-1.10.11");
    assert.ok(grievance);
    assert.equal(grievance.liveKey, "grievance_acknowledgment");
    assert.equal(grievance.canPublish, true);
    const strategies = report.rows.find((r) => r.requirementKey === "REQ-1.24.5");
    assert.ok(strategies);
    assert.equal(strategies.liveKey, "support_strategies");
    assert.equal(strategies.canPublish, true);
    const housemate = report.rows.find((r) => r.requirementKey === "REQ-1.35");
    assert.ok(housemate);
    assert.equal(housemate.liveKey, "housemate_informed_choice");
    assert.equal(housemate.canPublish, true);
    const belongings = report.rows.find((r) => r.requirementKey === "REQ-11.3.5");
    assert.ok(belongings);
    assert.equal(belongings.liveKey, "belongings_inventory");
    assert.equal(belongings.canPublish, true);
    const roomBoard = report.rows.find((r) => r.requirementKey === "REQ-11.3.9");
    assert.ok(roomBoard);
    assert.equal(roomBoard.liveKey, "hhs_room_board_agreement");
    assert.equal(roomBoard.canPublish, true);
    const hhsCert = report.rows.find((r) => r.requirementKey === "REQ-11.5");
    assert.ok(hhsCert);
    assert.equal(hhsCert.liveKey, "hhs_home_cert_annual");
    assert.equal(hhsCert.canPublish, true);
    const lease = report.rows.find((r) => r.requirementKey === "REQ-21.3.1");
    assert.ok(lease);
    assert.equal(lease.liveKey, "rhs_lease_agreement");
    assert.equal(lease.canPublish, true);
    const olLicense = report.rows.find((r) => r.requirementKey === "REQ-21.5");
    assert.ok(olLicense);
    assert.equal(olLicense.liveKey, "ol_rhs_license_4plus");
    assert.equal(olLicense.canPublish, true);

    const zoning = report.rows.find((r) => r.requirementKey === "REQ-1.11");
    assert.ok(zoning);
    assert.equal(zoning.liveKey, "zoning_life_safety");
    assert.equal(zoning.canPublish, true);
    assert.equal(zoning.canActivate, true);
    assert.equal(zoning.mintsStaffTask, false);
    const board = report.rows.find((r) => r.requirementKey === "REQ-1.14");
    assert.ok(board);
    assert.equal(board.liveKey, "governing_board_records");
    assert.equal(board.canPublish, true);
    const operating = report.rows.find((r) => r.requirementKey === "REQ-1.18");
    assert.ok(operating);
    assert.equal(operating.liveKey, "operating_policies");
    assert.equal(operating.canPublish, true);
    const hrp = report.rows.find((r) => r.requirementKey === "REQ-1.21");
    assert.ok(hrp);
    assert.equal(hrp.liveKey, "human_rights_plan");
    assert.equal(hrp.canPublish, true);
    const discharge = report.rows.find((r) => r.requirementKey === "REQ-1.22.c");
    assert.ok(discharge);
    assert.equal(discharge.liveKey, "person_discharge_process");
    assert.equal(discharge.canPublish, true);
    const health = report.rows.find((r) => r.requirementKey === "REQ-1.23");
    assert.ok(health);
    assert.equal(health.liveKey, "health_support_policies");
    assert.equal(health.canPublish, true);
    const loan = report.rows.find((r) => r.requirementKey === "REQ-1.28.7");
    assert.ok(loan);
    assert.equal(loan.liveKey, "emergency_loan_record");
    assert.equal(loan.canPublish, true);
    const largeLoan = report.rows.find((r) => r.requirementKey === "REQ-1.28.7.G");
    assert.ok(largeLoan);
    assert.equal(largeLoan.liveKey, "large_loan_disclosure_process");
    assert.equal(largeLoan.canPublish, true);
    const noGifts = report.rows.find((r) => r.requirementKey === "REQ-1.28.9");
    assert.ok(noGifts);
    assert.equal(noGifts.liveKey, "no_gifts_process");
    assert.equal(noGifts.canPublish, true);

    const upiDesignee = report.rows.find((r) => r.requirementKey === "REQ-1.15.1");
    assert.ok(upiDesignee);
    assert.equal(upiDesignee.liveKey, "upi_form_0_9_designee");
    assert.equal(upiDesignee.canPublish, true);
    assert.equal(upiDesignee.canActivate, false);
    assert.equal(upiDesignee.publication, "not_published");
    const upiUtilization = report.rows.find((r) => r.requirementKey === "REQ-1.15.6");
    assert.ok(upiUtilization);
    assert.equal(upiUtilization.liveKey, "upi_1056_utilization");
    assert.equal(upiUtilization.canPublish, true);
    assert.equal(upiUtilization.canActivate, false);
    const upiNotify = report.rows.find((r) => r.requirementKey === "REQ-1.15.15");
    assert.ok(upiNotify);
    assert.equal(upiNotify.liveKey, "upi_notify_usteps_termination");
    assert.equal(upiNotify.canPublish, true);
    assert.equal(upiNotify.canActivate, false);

    const fbaInitial = report.rows.find((r) => r.requirementKey === "REQ-3.3.3");
    assert.ok(fbaInitial);
    assert.equal(fbaInitial.liveKey, "fba_bsp");
    assert.equal(fbaInitial.canPublish, true);
    assert.equal(fbaInitial.canActivate, false);
    assert.equal(fbaInitial.publication, "not_published");
    const bspSubmit = report.rows.find((r) => r.requirementKey === "REQ-5.4.6");
    assert.ok(bspSubmit);
    assert.equal(bspSubmit.liveKey, "fba_bsp");
    assert.equal(bspSubmit.canPublish, true);
    assert.equal(bspSubmit.canActivate, false);
    const rightsMod = report.rows.find((r) => r.requirementKey === "REQ-3.4.3");
    assert.ok(rightsMod);
    assert.equal(rightsMod.liveKey, null);

    const hhsFy = report.rows.find((r) => r.requirementKey === "REQ-11.7.c");
    assert.ok(hhsFy);
    assert.equal(hhsFy.liveKey, "hhs_annual_outcome");
    assert.equal(hhsFy.canPublish, true);
    assert.equal(hhsFy.canActivate, false);
    assert.equal(hhsFy.publication, "not_published");
    const dsiFy = report.rows.find((r) => r.requirementKey === "REQ-8.6.c");
    assert.ok(dsiFy);
    assert.equal(dsiFy.liveKey, "dsi_annual_outcome");
    const seiFy = report.rows.find((r) => r.requirementKey === "REQ-30.7.c");
    assert.ok(seiFy);
    assert.equal(seiFy.liveKey, "sei_annual_outcome");
    const slhFy = report.rows.find((r) => r.requirementKey === "REQ-31.5.c");
    assert.ok(slhFy);
    assert.equal(slhFy.liveKey, "sl_annual_outcome");
    const slnFy = report.rows.find((r) => r.requirementKey === "REQ-32.7.c");
    assert.ok(slnFy);
    assert.equal(slnFy.liveKey, "sl_annual_outcome");
    const pn1Fy = report.rows.find((r) => r.requirementKey === "REQ-18.6.c");
    assert.ok(pn1Fy);
    assert.equal(pn1Fy.liveKey, "hhs_annual_outcome");
    assert.equal(pn1Fy.canActivate, false);
    const bc1Fy = report.rows.find((r) => r.requirementKey === "REQ-3.7.c");
    assert.ok(bc1Fy);
    assert.equal(bc1Fy.liveKey, "hhs_annual_outcome");

    const personReview = report.rows.find((r) => r.requirementKey === "REQ-1.28.5");
    assert.ok(personReview);
    assert.equal(personReview.liveKey, "pba_financial_review");
    assert.equal(personReview.canPublish, true);
    assert.equal(personReview.canActivate, true);
    assert.equal(personReview.mintsStaffTask, false);
    const pbaReviews = report.rows.find((r) => r.requirementKey === "REQ-15.3.7");
    assert.ok(pbaReviews);
    assert.equal(pbaReviews.liveKey, "pba_financial_review");
    assert.equal(pbaReviews.canPublish, true);
    assert.equal(pbaReviews.canActivate, true);
    assert.equal(pbaReviews.mintsStaffTask, false);

    const elements = report.rows.filter((r) => r.role === "element");
    assert.equal(elements.length, 607);
    assert.ok(elements.every((r) => r.mintsStaffTask === false));
    assert.ok(elements.every((r) => r.implementationStatus === "element_of_parent"));
  });
});
