-- Phase 2 platform requirement_defs seed (locked DHHS91172 catalog).
-- Additive INSERT/upsert only. No DROP. No invented SOW body text.
-- Titles and citations come from src/lib/sow-obligation-catalog.ts.
-- organization_id IS NULL = platform catalog (not PHI).
-- Idempotent on requirement_key for platform rows.

WITH seed (
  requirement_key,
  subject_kind,
  layer,
  title,
  source_sow_cite,
  gate_fact_key,
  default_on
) AS (
  VALUES
  ('abi_training', 'staff', 'staff_exception', 'ABI Training — Before Working Alone', 'DHHS91172 SOW §1.8 (ABI training)', 'abi_caseload', true),
  ('acre_sed', 'staff', 'staff_exception', 'ACRE Training Certification — SED', 'DHHS91172 SOW §28.4', NULL, true),
  ('acre_sei', 'staff', 'staff_exception', 'ACRE Training Certification — SEI', 'DHHS91172 SOW §30.5', NULL, true),
  ('acre_sjd', 'staff', 'staff_exception', 'ACRE Training Certification — SJD (60 Days)', 'DHHS91172 SOW §33.5', NULL, true),
  ('agency_license_register', 'org', 'company_standing', 'Agency License Register Leftovers', 'DHHS91172 SOW §1.4(3) / §1.34', NULL, true),
  ('baa_on_file', 'org', 'company_standing', 'Business Associate Agreements — On File', 'HIPAA — BAA', NULL, true),
  ('background_screening_annual', 'staff', 'all_staff_clock', 'Background Screening — Annual', 'DHHS91172 SOW §1.9(2)', NULL, true),
  ('bc_staff_qualifications', 'org', 'company_standing', 'BC Staff Qualifications Leftovers', 'DHHS91172 SOW §3.6 / §4.6 / §5.6', NULL, true),
  ('behavior_intervention_cert', 'staff', 'staff_exception', 'Behavior Intervention Certification (SOAR/MANDT/PART/CPI/Safety Care)', 'DHHS91172 SOW §1.8(6)', 'behavior_caseload', true),
  ('ce_12h_annual', 'staff', 'all_staff_clock', 'Annual 12-Hour Continuing Education', 'DHHS91172 SOW §1.9', NULL, true),
  ('client_specific_training', 'client', 'client_shelf', 'Client-Specific Training — [Client Name]', 'DHHS91172 SOW §1.8(4)(O)', NULL, true),
  ('cmp_cms_caregiver_comp', 'staff', 'staff_exception', 'DSPD New Caregiver Compensation Training — CMP/CMS', 'DHHS91172 SOW §32.5', NULL, true),
  ('cmp_cms_monthly_summaries', 'org', 'company_standing', 'CMP/CMS Monthly Summaries — Submitted to SC', 'DHHS91172 SOW §32.3', NULL, true),
  ('commerce_entity_standing', 'org', 'company_standing', 'Utah Department of Commerce — Entity Standing', 'Practice Audit — agency standing', NULL, true),
  ('conflict_of_interest_process', 'org', 'company_standing', 'Staff Conflict of Interest Process', 'CST 9 & 10', NULL, true),
  ('cpr_first_aid_initial', 'staff', 'all_staff_clock', 'CPR/First Aid Certification — Initial', 'DHHS91172 SOW §1.8(5)', NULL, true),
  ('cpr_first_aid_renewal', 'staff', 'all_staff_clock', 'CPR/First Aid Certification — Renewal', 'DHHS91172 SOW §1.8(5)', NULL, true),
  ('customized_employment_usu', 'staff', 'staff_exception', 'Customized Employment Training (USU) — SEE/SJD', 'DHHS91172 SOW §29.4 / §33.5', NULL, true),
  ('dhhs_code_of_conduct_posted', 'org', 'company_standing', 'DHHS Code of Conduct — Posted', 'CST 76', NULL, true),
  ('dhhs_code_of_conduct_signed', 'staff', 'staff_exception', 'DHHS Code of Conduct — Signed', 'CST 76', NULL, true),
  ('dhhs_quality_remediation', 'org', 'company_standing', 'DHHS Quality Remediation Plan Leftovers', 'DHHS91172 SOW §1.19', NULL, true),
  ('dlbc_group_variance', 'org', 'company_standing', 'DLBC Group Variance Leftovers', 'DHHS91172 SOW §1.32(c)', NULL, true),
  ('dnr_order_access', 'client', 'client_shelf', 'DNR Order Access Leftovers', 'DHHS91172 SOW §1.10(14)', NULL, true),
  ('driving_record_transport', 'staff', 'staff_exception', 'Driving Record — On File (Transporting Staff)', 'DHHS91172 SOW §1.30', 'does_not_transport', true),
  ('dsi_annual_outcome', 'org', 'company_standing', 'DSI Annual Outcome Report — Google Form Submission', 'DHHS91172 SOW §8.6', NULL, true),
  ('educational_credentials', 'staff', 'staff_shelf', 'Educational Credentials and Licenses — On File', 'DHHS91172 SOW §1.9(4)', NULL, true),
  ('els_residential_eligibility', 'org', 'company_standing', 'ELS Residential Eligibility Leftovers', 'DHHS91172 SOW §10.5', NULL, true),
  ('els_school_age', 'client', 'client_shelf', 'ELS School-Age Temporary Use Leftovers', 'DHHS91172 SOW §10.3(3)', NULL, true),
  ('em_bcp_plan', 'org', 'company_standing', 'Emergency Management and Business Continuity Plan', 'CST 46', NULL, true),
  ('em_bcp_training_annual', 'staff', 'all_staff_clock', 'Annual Emergency Management Plan Training', 'CST 46', NULL, true),
  ('employment_assessment_fade', 'org', 'company_standing', 'SED/SEE/SEI Assessment and Fade Leftovers', 'DHHS91172 SOW §28.2 / §29.2 / §30.2', NULL, true),
  ('epr_program_file', 'org', 'company_standing', 'EPR Program File Leftovers', 'DHHS91172 SOW §9.2 / §9.5', NULL, true),
  ('fatality_notification', 'org', 'company_standing', 'Fatality Notification Leftovers', 'DHHS91172 SOW §1.26', NULL, true),
  ('form_929_exceptional_care', 'client', 'client_shelf', 'Form 929 Exceptional-Care Respite Leftovers', 'DHHS91172 SOW §23.3(1) / §25.3(1)', NULL, true),
  ('governing_board_records', 'org', 'company_standing', 'Governing or Policy-Making Board Records', 'DHHS91172 SOW §1.14', 'has_governing_board', true),
  ('grievance_acknowledgment', 'client', 'client_shelf', 'Grievance Policy Acknowledgment — Signed', 'DHHS91172 SOW §1.10(11)', NULL, true),
  ('group_service_review_historical', 'org', 'company_standing', 'Historical Group Service Review Leftovers', 'DHHS91172 SOW §1.32(a)', NULL, true),
  ('health_support_policies', 'org', 'company_standing', 'Health Support Policies and Procedures', 'DHHS91172 SOW §1.23', NULL, true),
  ('hhs_annual_outcome', 'org', 'company_standing', 'HHS Annual Outcome Report — Google Form Submission', 'DHHS91172 SOW §11.7', NULL, true),
  ('hhs_evac_drills_quarterly', 'site', 'company_standing', 'HHS Quarterly Evacuation Drills — All Sites', 'DHHS91172 SOW §11.3', NULL, true),
  ('hhs_home_cert_annual', 'site', 'company_standing', 'HHS Home Certification — Annual (DSPD Form)', 'DHHS91172 SOW §11.5', NULL, true),
  ('hhs_room_board_agreement', 'client', 'client_shelf', 'HHS Room-and-Board Agreement', 'DHHS91172 SOW §11.3(9)', NULL, true),
  ('hipaa_npp', 'org', 'company_standing', 'HIPAA Notice of Privacy Practices', 'HIPAA — NPP', NULL, true),
  ('home_condition_checklist', 'org', 'company_standing', 'Home Condition Checklist Leftovers', 'DHHS91172 SOW §11.3(2) / §20.3(2) / §21.3(2)', NULL, true),
  ('host_contractor_change', 'org', 'company_standing', 'HHS/PPS Host Contractor-Change Leftovers', 'DHHS91172 SOW §11.3(8) / §20.3(8)', NULL, true),
  ('host_staff_qualifications', 'org', 'company_standing', 'HHS/PPS Host Staff Age Leftovers', 'DHHS91172 SOW §11.6 / §20.6', NULL, true),
  ('household_12plus_background', 'org', 'company_standing', 'Household 12+ Background Screening Leftovers', 'DHHS91172 SOW §11.3 / §20.3 / §22.3 / §23.3 / §24.3 / §25.3', NULL, true),
  ('housemate_informed_choice', 'client', 'client_shelf', 'Housemate Informed-Choice Discussion', 'DHHS91172 SOW §1.35', NULL, true),
  ('hsq_safe_environment', 'staff', 'staff_exception', 'HSQ — Clean, Sanitary & Safe Environment Training', 'DHHS91172 Article 12', NULL, true),
  ('human_rights_plan', 'org', 'company_standing', 'Human Rights Plan', 'DHHS91172 SOW §1.21', NULL, true),
  ('incident_reporting_process', 'org', 'company_standing', 'Incident Reporting Process', 'DHHS91172 SOW §1.27', NULL, true),
  ('iqmp', 'org', 'company_standing', 'Internal Quality Management Plan', 'CST 50', NULL, true),
  ('large_loan_disclosure_process', 'org', 'company_standing', 'Large-Loan Disclosure Process', 'DHHS91172 SOW §1.28(7)(G)', NULL, true),
  ('liability_insurance', 'org', 'company_standing', 'General, Professional, and Automobile Liability Insurance', 'CST 29–36', NULL, true),
  ('medicaid_101_contractor', 'org', 'company_standing', 'DHHS Medicaid 101 Training — Contractor', 'DHHS91172 SOW §1.7(1)', NULL, true),
  ('medicaid_change_notifications', 'org', 'company_standing', 'Medicaid Provider Change Notifications', 'DHHS91172 SOW §1.13(2)–(3)', NULL, true),
  ('medicaid_disclosure_annual', 'staff', 'all_staff_clock', 'Medicaid Disclosure Form — Annual', 'DHHS91172 SOW §1.9(6)', NULL, true),
  ('medicaid_eligibility_assist', 'client', 'client_shelf', 'Medicaid Eligibility Review Assistance Leftovers', 'DHHS91172 SOW §11.2 / §20.2 / §21.2 / §31.2', NULL, true),
  ('medicaid_enrollment', 'org', 'company_standing', 'Medicaid Provider Enrollment — Current', 'DHHS91172 SOW §1.4(1) / §1.13', NULL, true),
  ('medicaid_exclusion_annual', 'staff', 'all_staff_clock', 'Medicaid Fraud & Abuse Exclusion Screening — Annual', 'DHHS91172 SOW §1.9(7)', NULL, true),
  ('medicaid_manuals_memo', 'org', 'company_standing', 'Utah Medicaid Provider Manuals — Annual Memo', 'DHHS91172 SOW §1.7(2)–(4)', NULL, true),
  ('medicaid_provider_training_offered', 'org', 'company_standing', 'As-Offered Medicaid Provider Training Leftovers', 'DHHS91172 SOW §1.13(4)', NULL, true),
  ('medical_dental_exams', 'client', 'client_shelf', 'Medical and Dental Examinations — Person File', 'DHHS91172 SOW §1.23(h)(1)', NULL, true),
  ('milestone_rfs', 'org', 'company_standing', 'SJP/SJR Milestone Request for Services Leftovers', 'DHHS91172 SOW §34.3 / §35.3', NULL, true),
  ('no_gifts_process', 'org', 'company_standing', 'No Gifts or Purchases-from-Staff Process', 'DHHS91172 SOW §1.28(9)–(10)', NULL, true),
  ('ol_capacity_comply', 'org', 'company_standing', 'OL Capacity Comply Leftovers', 'DHHS91172 SOW §7.3(5) / §8.3(3) / §9.3(5) / §22.3(3) / §23.3(4) / §24.3(3) / §25.3(4) / §26.3(2)', NULL, true),
  ('ol_day_support_cert_3or_fewer', 'org', 'company_standing', 'OL Day Support Certification — 3 or Fewer Persons', 'DHHS91172 SOW §8.5 / §7.5', NULL, true),
  ('ol_day_tx_license_4plus', 'org', 'company_standing', 'OL Day Treatment License — 4+ Persons', 'DHHS91172 SOW §8.5 / §7.5', NULL, true),
  ('ol_rhs_cert_3or_fewer', 'org', 'company_standing', 'OL Residential Support Certification — 3 or Fewer Persons per Site', 'DHHS91172 SOW §21.5', NULL, true),
  ('ol_rhs_license_4plus', 'org', 'company_standing', 'OL Residential Support License — 4+ Persons per Site', 'DHHS91172 SOW §21.5', NULL, true),
  ('operating_policies', 'org', 'company_standing', 'Operating Policies and Procedures', 'DHHS91172 SOW §1.18', NULL, true),
  ('orientation_30_day', 'staff', 'all_staff_clock', '30-Day New Hire Orientation Training', 'DHHS91172 SOW §1.8(4)', NULL, true),
  ('pba_monthly_fiduciary', 'org', 'company_standing', 'PBA Monthly Fiduciary Leftovers', 'DHHS91172 SOW §15.2(6) / §15.2(10)', NULL, true),
  ('pcsp_person_review', 'client', 'client_shelf', 'PCSP Orientation and PCPT Review Leftovers', 'DHHS91172 SOW §1.24(7) / §1.24(9)', NULL, true),
  ('pct_hire_practices', 'staff', 'all_staff_clock', 'Person-Centered Thinking and Practices Training', 'DHHS91172 SOW §1.8(5)(C)', NULL, true),
  ('person_discharge_process', 'org', 'company_standing', 'Person Discharge Process', 'DHHS91172 SOW §1.22(c)', NULL, true),
  ('person_record_file', 'client', 'client_shelf', 'Person Record File Leftovers', 'DHHS91172 SOW §1.10', NULL, true),
  ('personnel_policies', 'org', 'company_standing', 'Personnel Policies and Job Descriptions', 'DHHS91172 SOW §1.17', NULL, true),
  ('pm_nursing_file', 'client', 'client_shelf', 'PM1/PM2 Nursing File — Medication Program Leftovers', 'DHHS91172 SOW §16.2 / §16.4 / §17.2 / §17.4', NULL, true),
  ('pn_medical_care_plan', 'client', 'client_shelf', 'PN1/PN2 Medical Care Plan — Nursing Leftovers', 'DHHS91172 SOW §18.2 / §18.5 / §19.2 / §19.5', NULL, true),
  ('pps_evac_drills_quarterly', 'site', 'company_standing', 'PPS Quarterly Evacuation Drills — All Sites', 'DHHS91172 SOW §20.3', NULL, true),
  ('pps_foster_license', 'staff', 'staff_exception', 'Child Placing / Foster Care License (DHHS/OL) — PPS', 'DHHS91172 SOW §20.5', NULL, true),
  ('pps_room_board_agreement', 'client', 'client_shelf', 'PPS Room-and-Board Agreement', 'DHHS91172 SOW §20.3', NULL, true),
  ('program_day_to_day_staff', 'org', 'company_standing', 'Day-to-Day Program Staff Leftovers', 'DHHS91172 SOW §7.3 / §9.3 / §10.3 / §21.3', NULL, true),
  ('residential_group_mix', 'org', 'company_standing', 'Residential Group-Mix Approval Leftovers', 'DHHS91172 SOW §1.32(b)', NULL, true),
  ('rhs_evac_drills_quarterly', 'site', 'company_standing', 'RHS Quarterly Evacuation Drills — All Sites', 'DHHS91172 SOW §21.3', NULL, true),
  ('rhs_form_930', 'client', 'client_shelf', 'RHS Form 930 Enhanced Staffing Leftovers', 'DHHS91172 SOW §21.3(4)', NULL, true),
  ('rhs_housing_voucher', 'client', 'client_shelf', 'RHS Housing Voucher Leftovers', 'DHHS91172 SOW §21.3(8)', NULL, true),
  ('rhs_lease_agreement', 'client', 'client_shelf', 'RHS Lease Agreement', 'DHHS91172 SOW §21.3(1)', NULL, true),
  ('sc_records_on_request', 'org', 'company_standing', 'Support Coordinator Records-on-Request Leftovers', 'DHHS91172 SOW §1.31(2) / §1.31(3)', NULL, true),
  ('sec_pass_documentation', 'org', 'company_standing', 'SEC Pass-Through and Co-Worker Support Leftovers', 'DHHS91172 SOW §27.3', NULL, true),
  ('sec_requires_sei', 'org', 'company_standing', 'SEC Requires SEI Leftovers', 'DHHS91172 SOW §27.5', NULL, true),
  ('see_staff_training', 'org', 'company_standing', 'SEE Staff Training Leftovers', 'DHHS91172 SOW §29.4', NULL, true),
  ('sei_annual_outcome', 'org', 'company_standing', 'SEI Annual Outcome Report — Google Form Submission', 'DHHS91172 SOW §30.7', NULL, true),
  ('sei_employment_data_upi', 'org', 'company_standing', 'SEI Employment Data — UPI Entry Attestation', 'DHHS91172 SOW §30.3', NULL, true),
  ('sei_employment_strategies_upi', 'org', 'company_standing', 'SEI Employment Support Strategies — UPI Entry', 'DHHS91172 SOW §30.3', NULL, true),
  ('sei_job_termination', 'org', 'company_standing', 'SEI Job-Termination Notice Leftovers', 'DHHS91172 SOW §30.3(3)', NULL, true),
  ('sei_monthly_summary_upi', 'org', 'company_standing', 'SEI Monthly Summary — UPI Entry Attestation', 'DHHS91172 SOW §30.3', NULL, true),
  ('sei_ssi_benefits', 'staff', 'staff_exception', 'SEI — SSI/Benefits Knowledge Attestation', 'DHHS91172 SOW §30.5', NULL, true),
  ('sjd_discovery_vocational', 'org', 'company_standing', 'SJD Discovery / Vocational Assessment Leftovers', 'DHHS91172 SOW §33.2', NULL, true),
  ('sjd_employment_data_upi', 'org', 'company_standing', 'SJD Employment Data — UPI Entry Attestation', 'DHHS91172 SOW §33.3', NULL, true),
  ('sjd_monthly_summary_upi', 'org', 'company_standing', 'SJD Monthly Summary — UPI Entry Attestation', 'DHHS91172 SOW §33.3', NULL, true),
  ('sjd_usor_contact_monthly', 'org', 'company_standing', 'SJD Monthly USOR Contact Verification', 'DHHS91172 SOW §33.3', NULL, true),
  ('sjp_requires_sjd', 'org', 'company_standing', 'SJP Requires SJD Leftovers', 'DHHS91172 SOW §34.5', NULL, true),
  ('sjr_requires_see_or_sei', 'org', 'company_standing', 'SJR Requires SEE or SEI Leftovers', 'DHHS91172 SOW §35.5', NULL, true),
  ('sl_annual_outcome', 'org', 'company_standing', 'Supported Living Annual Outcome Report — Google Form Submission', 'DHHS91172 SOW §31.5 / §32.7', NULL, true),
  ('staff_minimum_age', 'staff', 'staff_shelf', 'Staff Minimum Age System Check Leftovers', 'DHHS91172 SOW §1.5', NULL, true),
  ('support_strategies', 'client', 'client_shelf', 'Support Strategies — [Client Name]', 'DHHS91172 SOW §1.24(5)', NULL, true),
  ('tfb_staff_qualifications', 'org', 'company_standing', 'TFB Staff Qualifications Leftovers', 'DHHS91172 SOW §36.4', NULL, true),
  ('training_file_maintained', 'staff', 'staff_shelf', 'Training Documentation File — Maintained', 'DHHS91172 SOW §1.9(3)', NULL, true),
  ('upi_1056_decision', 'org', 'company_standing', 'UPI 1056 Approve or Reject', 'DHHS91172 SOW §1.15(4)', NULL, true),
  ('upi_1056_reject_coordinate', 'org', 'company_standing', 'UPI 1056 Rejection — Support Coordinator Coordination', 'DHHS91172 SOW §1.15(5)', NULL, true),
  ('upi_annual_access_review', 'org', 'company_standing', 'UPI Annual Staff Access Review', 'DHHS91172 SOW §1.15(14)', NULL, true),
  ('upi_employee_registry', 'org', 'company_standing', 'UPI Employee Registry Leftovers', 'DHHS91172 SOW §30.8(1) / §33.7(1)', NULL, true),
  ('upi_employee_timesheet', 'org', 'company_standing', 'UPI Employee Timesheet Leftovers', 'DHHS91172 SOW §30.8(2) / §33.7(2)', NULL, true),
  ('upi_form_0_8_user', 'org', 'company_standing', 'UPI Form 0-8 — Individual User Access', 'DHHS91172 SOW §1.15(2)', NULL, true),
  ('upi_form_0_9_designee', 'org', 'company_standing', 'UPI Form 0-9 — Provider Company Designee Access', 'DHHS91172 SOW §1.15(1)', NULL, true),
  ('upi_need_to_know_access', 'org', 'company_standing', 'UPI Need-to-Know Access', 'DHHS91172 SOW §1.15(3)', NULL, true),
  ('upi_notify_usteps_termination', 'org', 'company_standing', 'Notify DSPD USTEPS of UPI Staff Termination — One Calendar Day', 'DHHS91172 SOW §1.15(15)', NULL, true),
  ('upi_person_org_groups', 'org', 'company_standing', 'UPI Person Organizational Groups', 'DHHS91172 SOW §1.15(10)', NULL, true),
  ('upi_provider_organization', 'org', 'company_standing', 'UPI Provider Organization Structure', 'DHHS91172 SOW §1.15(7)', NULL, true),
  ('upi_remove_discharged_person', 'org', 'company_standing', 'UPI Remove Discharged Person from Provider Organization', 'DHHS91172 SOW §1.15(13)', NULL, true),
  ('upi_remove_staff_need_to_know', 'org', 'company_standing', 'UPI Remove Staff Need-to-Know — One Calendar Day', 'DHHS91172 SOW §1.15(12)', NULL, true),
  ('upi_remove_terminated_staff', 'org', 'company_standing', 'UPI Remove Terminated Staff — One Calendar Day', 'DHHS91172 SOW §1.15(11)', NULL, true),
  ('upi_staff_notify_prefs', 'org', 'company_standing', 'UPI Staff Email and Notification Preference', 'DHHS91172 SOW §1.15(9)', NULL, true),
  ('upi_staff_org_groups', 'org', 'company_standing', 'UPI Staff Organizational Groups', 'DHHS91172 SOW §1.15(8)', NULL, true),
  ('usdc_transition', 'client', 'client_shelf', 'USDC Transition Coordination Leftovers', 'DHHS91172 SOW §1.36', NULL, true),
  ('usor_job_coaching_sei', 'org', 'company_standing', 'USOR Approved Vendor — Job Coaching (SEI)', 'DHHS91172 SOW §30.5', NULL, true),
  ('usor_job_development_sjd', 'org', 'company_standing', 'USOR Approved Vendor — Job Development (SJD)', 'DHHS91172 SOW §33.5', NULL, true),
  ('usteps_upi_accounts', 'org', 'company_standing', 'USTEPS and UPI Contractor Accounts', 'DHHS91172 SOW §1.4(2) / §1.15', NULL, true),
  ('volunteer_training_file', 'org', 'company_standing', 'Volunteer Training File — When Volunteers Are Used', 'DHHS91172 SOW §1.6', 'uses_volunteers', true),
  ('zoning_life_safety', 'org', 'company_standing', 'Zoning / Life Safety Code Compliance Documentation', 'DHHS91172 SOW §1.11', 'operates_ol_site', true)
)
INSERT INTO public.requirement_defs (
  organization_id,
  requirement_key,
  subject_kind,
  layer,
  title,
  source_sow_cite,
  gate_fact_key,
  default_on
)
SELECT
  NULL,
  s.requirement_key,
  s.subject_kind,
  s.layer,
  s.title,
  s.source_sow_cite,
  s.gate_fact_key,
  s.default_on
FROM seed s
ON CONFLICT (requirement_key) WHERE organization_id IS NULL
DO UPDATE SET
  subject_kind = EXCLUDED.subject_kind,
  layer = EXCLUDED.layer,
  title = EXCLUDED.title,
  source_sow_cite = EXCLUDED.source_sow_cite,
  gate_fact_key = EXCLUDED.gate_fact_key,
  default_on = EXCLUDED.default_on,
  updated_at = now();
